devfolioco/react-otp-input

- README.md
- package-lock.json
- package.json
- src/demo/index.jsx
- src/lib/index.jsx
> Prop to restrict input to numbers

- package.json
- src/lib/index.jsx
> Fix uncontrolled to controlled input error

- package.json
- src/demo/index.jsx
- src/demo/styles.css
- src/lib/index.jsx
• Adds value prop to OTP input
• With that value, it's possible to clear inputs value
• Fixes maxLength when input is number type
- **Related issues:**
• Clear inputs: #7 
• event.keycode on keyboardEvent is deprecated  #18
• when input type is number maxLength=1 attribute is ignored #21
> Allow clear values and update input text, and fixes number input maxLength

- src/lib/index.jsx
- Update Demo in CodeSandbox with new version
- Fix warning when `className` has `undefined` value
> Remove warning when className has undefined

- package-lock.json
- src/demo/styles.css
This PR removes the arrows appearing in the input when 'isInputNum' is checked. This makes the UI more consistent to when isInputNum is not checked and makes it more like an actual OTP input form.
Currently, when isInputNum = true, the inputs show up and down arrows which shifts the number to the left. Example: 
This PR removes those arrows and makes the UI more consistent.
> Number input style fix

- src/lib/index.jsx
Now **space** will not be taken as input. Pressing space will do nothing
> Fixed issue #38 of space input

- README.md
> Corrected readme file

- src/demo/index.jsx
- src/demo/styles.css
Fixes #69 
Made demo site mobile responsive by adding CSS media queries.
Browser - Mozilla Firefox 69.0
> Fixes demo site responsiveness issue

- .gitignore
- .travis.yml
- package-lock.json
- package.json
> Added codecov

- README.md
i think this gif is more suitable to explain the app..
https://media.giphy.com/media/lN98dFU6h3oP0wWS5x/giphy.gif
> Hacktoberfest-Added suitable gif image..see https://media.giphy.com/media/lN98dFU6h3oP0wWS5x/giphy.gif

- .eslintrc.json
- package-lock.json
- package.json
- src/lib/index.jsx
It fixes #35 by Refactoring Class Components to Functional Components.
Also updates flow-bin dependency and add @types/react for better type-checking.
> Migrate to Hooks | Update Flow

- README.md
>  ❤️ for the badges.
**Added few badges:**
1. `npm` badges 
[![npm version](https://badge.fury.io/js/react-otp-input.svg)](https://badge.fury.io/js/react-otp-input) [![npm](https://img.shields.io/npm/dw/react-otp-input.svg?logo=npm)](https://www.npmjs.com/package/react-otp-input) 
[![NPM](https://nodei.co/npm/react-otp-input.png?compact=true)](https://nodei.co/npm/react-otp-input/)
2. [Shields](https://shields.io/) badges
[![GitHub issues](https://img.shields.io/github/issues-raw/devfolioco/react-otp-input?logo=github)](https://github.com/devfolioco/react-otp-input/issues) [![GitHub pull requests](https://img.shields.io/github/issues-pr/devfolioco/react-otp-input?logo=git)](https://github.com/devfolioco/react-otp-input/pulls)
3. PRs welcome badges
[![PRs …
> Prettified README.md with badges

- LICENSE
- src/demo/index.jsx
- src/lib/index.jsx
- Sets a min and max otp input length in the demo.
- Lint fixes.
NA
NA
> :recycle: Demo: Update numInputs range

- src/lib/index.jsx
Fixes #20 
When the user entered a number in input with the same number, the next input did not get focused. This PR fixes that.
> Fixed same input not triggering next focus

- src/demo/index.jsx
Added an input name check in range condition to prevent false errors.
NA
https://roi2.surge.sh
> :bug: Demo: Add numInputs error condition

- .babelrc
- src/lib/index.jsx
Fixes #25, fixes #29, fixes #30, fixes #50, fixes #71, fixes #81, fixes #85, fixes #97
NA
https://roi2.surge.sh
> :recycle: Updates to the isInputNum behaviour

- README.md
> :bug: Fix sample code + Update CodeSandbox URL

- README.md
Hide placeholder up until next release.
> :pencil2: Update README

- README.md
> updated doc

- src/lib/index.jsx
Adds `aria-label` attribute to input elements, as discussed in issue #102
> add aria-label to input element

- README.md
Fixes #162
Removed incorrect commands, while adding a new to do task that can be followed up
> remove old links from readme

- src/demo/index.jsx
> :bug: Demo: Fix placeholder not working when numInputs change

- .github/workflows/github-page.yml
- example/package.json
- example/vite.config.ts
- example/yarn.lock
- package.json
- tsconfig.json
Fix GitHub action that deploys example to GitHub action by adding a base path to vite config
> Fix example deploy GitHub action

- package.json
- src/index.tsx
> ♻️ Export all types for react-otp-input
