devfolioco/react-otp-input

src/lib/index.jsx
When passing custom props to HTML components React will throw a warning that says it doesn't recognize this prop. Since the prop is camel-cased (`shouldAutoFocus`), as opposed to lower-case (`shouldautofocus`), React tries to recognize it instead of just pass it to the DOM element.
The solution is the deconstructure it along with the used props so it won't get passed in `{...rest}`.
=> Don't pass `shouldAutoFocus` to <input />

LICENSE, README.md
update license to include 2019 as license valid time. Shall raise an issue to fix this as it can be easily overlooked and a permanent solution needs to be done.
update the license to include 2019 as covered year too
=> update license to include 2019

src/demo/index.jsx, src/demo/styles.css
This PR is for the demo site and it adds a wrap property to the singleOtpBox flex container so that a higher numInputs value doesn't let the container overflow. I have also added a min value for the numInputs input box so that it doesn't take in a negative value.
**Before** fixing the singleOtpBox container overflow issue.
**Before** fixing the numInputs input box taking negative values.
**After** fixing the singleOtpBox container overflow issue.
=> Demo-site : Minor css and html changes

.gitignore, README.md, docs/index.mdx, package-lock.json, package.json, src/lib/index.jsx
Added Docz documentation initial setup
https://github.com/devfolioco/react-otp-input/issues/36
https://5d964f327aeaa4000813eff2--competent-ride-bdb7ab.netlify.com/docs-index
This is not yet completed. this is just the setup part.
I have deployed the site in netlify using this branch https://github.com/anikethsaha/react-otp-input/tree/docz/netlify-preview
One thing I faced while deploying was that we need to add the `.docz` folder which comes out when running `yarn docz:build` cause in netlify even after running the `npm run build && npm run docz:build` there, I guess some errors was there regarding the creation of `.docz/public` folder cause it was showing it's not able to …
=> docs: added initial docz setup for documentation

src/demo/styles.css
Fixes #83 
Modified appearance for input type="number" to `textfield` with different browsers support.
Browser - Firefox - 69.0
=> Fixes issues related to arrow keys appearing in firefox browser on isInputNum field enabled

src/demo/index.jsx
Even when is disabled is activated clear button is clearing the OTP. So when disabled is activated we need to disable the clear button.
=> Disable Clear if isDisabled activated

src/demo/index.jsx
This pull request restricts the value of numInputs length bw 0 and 10.
if user enters negative value it converts into 0.
if user enters value greater than 10, it converts into 10 and a alert is shown stating that max value is 10.
=> Limits length of numInputs

src/lib/index.jsx
Fixes the bug where when entering an otp that starts with zero the entire otp value would be cleared
=> Fix bug with otp codes starting with zero being stripped

src/lib/index.jsx
Exposes the `className` prop which styled-components requires to correctly style components.
See documentation on "styling any component": https://styled-components.com/docs/basics#styling-any-component
=> Passing className as a prop for styled-components support

README.md, src/lib/index.jsx
**What does this PR do?**
- Added placeholder support.
- User can pass a string as placeholder prop
- If the string is of length 1, the character will be repeated across all inputs
- If the placeholder is of length `numLengths`, each character will be used as a placeholder for each input respectively.
- Will throw an error for invalid placeholder length.
- Fix #117 
**Demo**
- Placeholder is "1234" 
- Placeholder is "1"
=> Added Placeholder support

src/demo/index.jsx
currently, the clear button is **active** even if OTP input fields are empty which doesn't have any use when the field is empty. This PR will fix this issue and make clear button **disabled** when the input field of OTP is empty. Fix #158 
**Before Fix of this issue**
**After Fix of this issue**
=> disable clear button when otp field is empty

src/demo/styles.css
**What does this PR do?**
currently disable buttons cursor type is default, but for disable buttons not-allowed cursor type is more relevant. This PR will fix this small issue. fix #158 
**Screenshots and/or Live Demo**
**Before fix**:-
**After Fix**:-
=> styled disabled btn cursor to not-allowed

README.md
Fixes #209 
Docz also tries to render our README as an MDX style documentation file. Unfortunately, the docz server doesnt run when we comment anything in the README file. We had a comment in the README file, and this PR fixes it.
=> Remove comment in README to run Docz server

README.md, src/demo/index.jsx, src/lib/index.jsx
fixes #115 
exposes a new property named isSecure to mask input characters
=> fix#115 : Add isSecure property

src/lib/index.jsx
When pasting a number copied earlier, the focus of the field does not change. This PR fixes that issue #121 
=> Input field focus change on copy pasted data

.github/workflows/github-page.yml
- Added GitHub action to automatically build and deploy the demo page to Github pages
- This happens in every push to the `master`
- Inspired from [devfolioco/react-copy-mailto](https://github.com/devfolioco/react-copy-mailto) & [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action)
- fix #225
=> Added github action to build and deploy demo

src/lib/index.jsx
Fixes https://github.com/devfolioco/react-otp-input/issues/96
Continues https://github.com/devfolioco/react-otp-input/pull/206
This PR aims to add `data-cy` support for cypress E2E tests, and `data-testid` for react-testing-library tests.
Am using this library right now, but with my E2E tests I had to target `aria-label` which is not very resilient to changes.
With data attributes set in the demo:
Without data attributes set in the demo:
=> Add data attributes for test support

src/index.tsx
Fixes #388 
In android, event.code has no value if user click backspace. However, event.key has "backspace" value so instead of just checking event.code, event.key also must be checked.
=> fix: android backspace not working

README.md, package.json, src/index.tsx
**What does this PR do?**
- Adds a condition in onKeyDown to prevent character inputs in Firefox when input type is `number`, because Firefox allows non-number inputs for input type `number`
- Adds a warning to avoid people from overriding important `inputProps` provided by `renderInput`
Fixes #393
=> Fix number input accepting characters in Firefox

README.md, example/src/App.tsx, package.json, src/index.tsx
Fixes #399 
This bug was apparently introduced with #396, have found a better way to prevent that issue by preventing not allowed characters in `onInput`
=> 🚑  Fix paste not working for number inputs

README.md, src/index.tsx
Adds the ability to pass in an "onPaste" handler to the wrapper component to handle content getting pasted into the input fields.
We needed this functionality. Our solution was to wrap `OTPInput` in a `div` that did this but thought it might be useful to others if the component just supported it.
=> Support onPaste event handler
